@startuml

card Construction [
<b>(Re)construction</b>
--
- Development of firmware and hardware
- Development of firmware updates
==
- Hue gen 1: <i><color:blue>October 2012</color></i>
- Hue gen 2: <i><color:blue>October 2015</color></i>
- Hue gen 3: <i><color:blue>October 2016</color></i>
- Hue gen 4: <i><color:blue>December 2017</color></i>
]

card Production [
<b>Production</b>
--
- Mass produce light bulbs
- Support different sockets
]

card Update [
<b>Update</b>
--
- Firmware update deployment
]

card IC [
<b>Installation and Commissioning</b>
--
- Install light bulbs
- Connect to power
- Connect to Hue Bridge using ZLL
- Form network
]

card Operation [
<b>Operation</b>
--
- Receive commands from network
- Redirect commands through network
- Possibly poll updates from bridge
]

card Decommissioning [
<b>Decommissioning</b>
--
- Factory reset
- Remove from socket
- End of life (lifespan of bulb)
]

Construction -> Update
Construction -> Production
Update --> Operation
Operation --> Update
Production --> IC
IC --> Operation
Operation -> Decommissioning
IC <- Decommissioning
@enduml