@startuml

card Construction [
<b>(Re)construction</b>
--
- Development of firmware and hardware
- Development of firmware updates
]

card Production [
<b>Production</b>
--
- Mass produce devices
- Flash firmware
]

card Update [
<b>Update</b>
--
- Firmware update deployment
]

card IC [
<b>Installation and Commissioning</b>
--
- Place or install device
- Connect to power or battery
- Connect to Hue Bridge using Zigbee
- Form network
]

card Operation [
<b>Operation</b>
--
- Send commands to bridge or light bulb
- Redirect commands through network
- Possibly poll updates from bridge
]

card Decommissioning [
<b>Decommissioning</b>
--
- Factory reset
- Physical removal of device
- End of life
]

Construction -> Update
Construction -> Production
Update --> Operation
Operation --> Update
Production --> IC
IC --> Operation
Operation -> Decommissioning
IC <- Decommissioning
@enduml