@startuml

card Construction [
<b>(Re)construction</b>
--
- Development of firmware and hardware
- Development of firmware updates
==
- Bridge gen 1: <i><color:blue>October 2012</color></i>
- Bridge gen 2: <i><color:blue>October 2015</color></i>
]

card Production [
<b>Production</b>
--
- Mass produce bridges
- Flash firmware
]

card Update [
<b>Update</b>
--
- Firmware update deployment
- Bridge service deployment
- Bridge service reconfiguration
]

card IC [
<b>Installation and Commissioning</b>
--
- Install device
- Connect to power
- Connect to LAN
- Connect to Hue app
- Connect to light and controller nodes
- (optionally) Connect to third party lights and apps
- Form network
]

card Operation [
<b>Operation</b>
--
- Send messages to nodes
- Receive messages from nodes
- Redirect commands through network
- Possibly send updates to nodes
- Retrieve updates from backend services
]

card Decommissioning [
<b>Decommissioning</b>
--
- Factory reset
- Disconnect from LAN
- Disconnect from power
- Physical removal of device
- End of life
]

Construction -> Update
Construction -> Production
Update --> Operation
Operation --> Update
Production --> IC
IC --> Operation
Operation -> Decommissioning
IC <- Decommissioning
@enduml